In [1]:
import torch  # 命令行是逐行立即执行的

content = torch.load('./pth_model/loc-batch256-epoch100-loss-2022101715.pth')

print(content.keys())  # keys()
# 之后有其他需求比如要看 key 为 model 的内容有啥
print(content['model']['linear.weight'].shape)
print(content['model']['linear.weight'])

dict_keys(['model'])
torch.Size([1024, 1024])
tensor([[-0.0175, -0.0259, -0.0270,  ..., -0.0176, -0.0264,  0.0266],
        [ 0.0219,  0.0117,  0.0124,  ...,  0.0102, -0.0174,  0.0050],
        [ 0.0070,  0.0017,  0.0256,  ..., -0.0271, -0.0290, -0.0295],
        ...,
        [ 0.0074,  0.0074, -0.0297,  ..., -0.0246,  0.0028, -0.0198],
        [ 0.0093, -0.0001, -0.0246,  ..., -0.0175, -0.0094, -0.0028],
        [-0.0205,  0.0287,  0.0310,  ...,  0.0113, -0.0238, -0.0208]],
       device='cuda:0')


In [40]:
import torch
import pandas as pd
import numpy as np
import os
# init embeddings
loc_index = pd.read_csv('../../data/loc_index.csv',index_col=0)
loc_size = len(loc_index)
embed_size = 256
sgm = 0.8
lbd = 0.6
cwd = os.path.abspath('.')
embed_256 = np.random.randn(loc_size, embed_size)
np.save('data/Geolife/embedding_256.npy', embed_256)

# drop掉label为-1的轨迹
all_traj = pd.read_hdf(cwd+"/all_traj_labeled_σ_{sgm}_λ_{lbd}.h5".format(sgm=sgm, lbd=lbd), key='data')
all_data = all_traj.drop(all_traj[all_traj['label']==-1].index)




In [42]:
all_traj.to_csv('./all_traj.csv')

In [43]:
os.getcwd()

'/home/lizhenyu/Project/E2DTC/feature_learning/bert'

In [15]:
import pandas as pd
import os
sgm = 0.8
lbd = 0.6
train_dataset = 'all_traj_labeled_σ_{sgm}_λ_{lbd}.h5'.format(sgm=sgm, lbd=lbd)

train_df = pd.read_hdf(os.path.join('./data/Geolife/', train_dataset), key='data')
train_df = train_df.drop(train_df[train_df['label'] == -1].index)

In [27]:
import torch
embeddings = torch.empty(1,256)
embeddings

tensor([[ 4.5609e+00,  4.5605e-41,  4.5609e+00,  4.5605e-41,  1.0310e+05,
          3.0854e-41,  1.0310e+05,  3.0854e-41,  1.4013e-45,  0.0000e+00,
          1.0310e+05,  3.0854e-41,  1.4013e-45,  0.0000e+00,  1.0310e+05,
          3.0854e-41,  3.3631e-44,  4.5605e-41, -8.7793e+20,  4.5602e-41,
          2.8026e-45,  4.5605e-41,  1.0310e+05,  3.0854e-41,  2.8026e-45,
          0.0000e+00,  2.8026e-45,  1.4013e-44,  3.3631e-44,  0.0000e+00,
          9.0266e-03,  4.5605e-41,  1.4013e-45,  0.0000e+00,  1.4013e-45,
          0.0000e+00,  2.8026e-45,  1.8217e-44,  2.8026e-45,  2.5223e-44,
          2.9427e-44,  0.0000e+00,  1.0310e+05,  3.0854e-41,  1.5323e+00,
          4.5605e-41,  1.4013e-45,  3.0854e-41,  2.8026e-45,  1.8217e-44,
          2.8026e-45,  3.3631e-44,  2.8026e-45,  0.0000e+00,  1.0310e+05,
          3.0854e-41,  1.0310e+05,  3.0854e-41,  2.8026e-44,  4.5602e-41,
         -1.3655e+02,  3.0852e-41,  0.0000e+00,  0.0000e+00,  3.9236e-44,
          0.0000e+00,  2.8026e-45,  3.

In [33]:
import pickle
def load_label(labelpath):
    '''
    Load label data: numpy array (datasize,)
    '''
    f = open(labelpath, 'rb')
    y = pickle.load(f)
    return y
Y = load_label('../../data/labels.pkl')
Y

array([ 1,  5,  1, ...,  0, 10,  9], dtype=int32)

In [38]:
print(Y.shape)

(86113,)


In [11]:
cluster_value_counts = pd.DataFrame(columns=['Num','Percentage'])
cluster_value_counts['Num'] = train_df['label'].value_counts().sort_index()

In [14]:
cluster_value_counts['Percentage'] =cluster_value_counts['Num']/len(train_df
                                                                )
cluster_value_counts['Percentage'] = cluster_value_counts['Percentage'].apply(lambda x: format(x, '.2%'))
cluster_value_counts

Num Percentage
0    52     18.91%
1     7      2.55%
2     9      3.27%
3    87     31.64%
4     3      1.09%
5    46     16.73%
6     9      3.27%
7    13      4.73%
8    21      7.64%
9     1      0.36%
10   27      9.82%