In [1]:
import torch  # 命令行是逐行立即执行的

content = torch.load('./pth_model/loc-batch256-epoch100-loss-2022101715.pth')

print(content.keys())  # keys()
# 之后有其他需求比如要看 key 为 model 的内容有啥
print(content['model']['linear.weight'].shape)
print(content['model']['linear.weight'])

dict_keys(['model'])
torch.Size([1024, 1024])
tensor([[-0.0175, -0.0259, -0.0270,  ..., -0.0176, -0.0264,  0.0266],
        [ 0.0219,  0.0117,  0.0124,  ...,  0.0102, -0.0174,  0.0050],
        [ 0.0070,  0.0017,  0.0256,  ..., -0.0271, -0.0290, -0.0295],
        ...,
        [ 0.0074,  0.0074, -0.0297,  ..., -0.0246,  0.0028, -0.0198],
        [ 0.0093, -0.0001, -0.0246,  ..., -0.0175, -0.0094, -0.0028],
        [-0.0205,  0.0287,  0.0310,  ...,  0.0113, -0.0238, -0.0208]],
       device='cuda:0')


In [72]:
batch=0
start=255
c = [1,2,3]

c[start-batch:start]


[]

In [60]:
import torch
import pandas as pd
import numpy as np
import os

x1 = torch.tensor([[1,2,3],[1,2,3]])
x2 = torch.tensor([[4,4,4],[4,4,4]])
y = torch.cat((x1, x2), dim=1)
y

tensor([[1, 2, 3, 4, 4, 4],
        [1, 2, 3, 4, 4, 4]])

In [42]:
all_traj.to_csv('./all_traj.csv')

In [43]:
os.getcwd()

'/home/lizhenyu/Project/E2DTC/feature_learning/bert'

In [15]:
import pandas as pd
import os
sgm = 0.8
lbd = 0.6
train_dataset = 'all_traj_labeled_σ_{sgm}_λ_{lbd}.h5'.format(sgm=sgm, lbd=lbd)

train_df = pd.read_hdf(os.path.join('./data/Geolife/', train_dataset), key='data')
train_df = train_df.drop(train_df[train_df['label'] == -1].index)

In [44]:
import pandas
embed_size = 256
sgm = 0.8
lbd = 0.6
cwd = os.path.abspath('.')
# traj_path = cwd+"/all_traj_labeled_σ_{sgm}_λ_{lbd}.h5".format(sgm=sgm, lbd=lbd)
traj_path = cwd+'/data/E2DTC/data.h5'
embed_path = './data/Geolife/embed_256.pt'
# embed_256 = np.random.randn(loc_size, embed_size)
# np.save('data/Geolife/embedding_256.npy', embed_256)

# drop掉label为-1的轨迹
all_traj = pd.read_hdf(traj_path, key='data')
all_data = all_traj.drop(all_traj[all_traj['label']==-1].index)
labels = np.array(all_data['label'])
embeddings = torch.load(embed_path).cpu().detach().numpy()

In [56]:
traj_path = cwd+'/data/E2DTC/data.h5'
# traj_path = cwd+"/all_traj_labeled_σ_{sgm}_λ_{lbd}.h5".format(sgm=sgm, lbd=lbd)
embed_path = './data/E2DTC/embed_256_epoch_150.pt'
all_traj = pd.read_hdf(traj_path)
embeddings = torch.load(embed_path).cpu().detach().numpy()

In [57]:
all_traj

trajectory  user_index  day  \
0      61 9 61 9 61 86 61 86 61 209 86 209 86 209 86 ...           1    1   
1      42 92 42 92 129 42 129 562 129 144 129 144 129...           1    1   
2      146 209 146 468 86 146 86 146 468 86 468 146 2...           1    1   
3      475 76 143 76 475 76 475 76 475 73 76 143 475 ...           1    1   
4      26 156 5 26 72 26 156 72 26 156 26 156 26 72 2...           1    1   
...                                                  ...         ...  ...   
66142  177 35 218 35 344 35 85 80 85 36 80 36 204 36 ...           1    1   
66143  10 103 10 103 10 103 10 103 10 103 10 [PAD] [P...           1    1   
66144  12 42 129 256 325 843 325 381 812 657 [PAD] [P...           1    1   
66145  24 16 24 16 33 16 33 115 33 115 33 16 33 16 33...           1    1   
66146  31 63 102 63 102 63 31 102 31 63 102 63 18 63 ...           1    1   

       year  month  index  label  
0         1      1      0      1  
1         1      1      1      5  
2         1      1      2      1  
3         1      1      3      9  
4         1      1      4      0  
...     ...    ...    ...    ...  
66142     1      1  86106      6  
66143     1      1  86107      9  
66144     1      1  86108      5  
66145     1      1  86109      8  
66146     1      1  86111     10  

[66147 rows x 7 columns]

In [33]:
import pickle
def load_label(labelpath):
    '''
    Load label data: numpy array (datasize,)
    '''
    f = open(labelpath, 'rb')
    y = pickle.load(f)
    return y
Y = load_label('../../data/labels.pkl')
Y

array([ 1,  5,  1, ...,  0, 10,  9], dtype=int32)

In [38]:
print(Y.shape)

(86113,)


In [11]:
cluster_value_counts = pd.DataFrame(columns=['Num','Percentage'])
cluster_value_counts['Num'] = train_df['label'].value_counts().sort_index()

In [14]:
cluster_value_counts['Percentage'] =cluster_value_counts['Num']/len(train_df
                                                                )
cluster_value_counts['Percentage'] = cluster_value_counts['Percentage'].apply(lambda x: format(x, '.2%'))
cluster_value_counts

Num Percentage
0    52     18.91%
1     7      2.55%
2     9      3.27%
3    87     31.64%
4     3      1.09%
5    46     16.73%
6     9      3.27%
7    13      4.73%
8    21      7.64%
9     1      0.36%
10   27      9.82%