In [103]:
import pandas as pd
import numpy as np
import pickle
import h5py
from collections import Counter

'''
把data_cdr.h5转换成E2DTC能跑的格式
'''


'\n把data_cdr.h5转换成E2DTC能跑的格式\n'

In [124]:
%%time
# 统计vocab_size, 重新编号
dataset = pd.read_hdf('./CDR/processed/data_cdr.h5',key='data')
data = dataset['trajectory']
trajs = []
for i, traj in enumerate(data):
    print(f'Traj {i}')
    traj_list = traj.split()
    traj_list = list(filter(lambda x: x != '[PAD]', traj.split(' ')))
    traj_list = list(map(lambda x: int(x), traj_list))
    trajs = trajs + traj_list
trajs

Traj 0
Traj 1
Traj 2
Traj 3
Traj 4
Traj 5
Traj 6
Traj 7
Traj 8
Traj 9
Traj 10
Traj 11
Traj 12
Traj 13
Traj 14
Traj 15
Traj 16
Traj 17
Traj 18
Traj 19
Traj 20
Traj 21
Traj 22
Traj 23
Traj 24
Traj 25
Traj 26
Traj 27
Traj 28
Traj 29
Traj 30
Traj 31
Traj 32
Traj 33
Traj 34
Traj 35
Traj 36
Traj 37
Traj 38
Traj 39
Traj 40
Traj 41
Traj 42
Traj 43
Traj 44
Traj 45
Traj 46
Traj 47
Traj 48
Traj 49
Traj 50
Traj 51
Traj 52
Traj 53
Traj 54
Traj 55
Traj 56
Traj 57
Traj 58
Traj 59
Traj 60
Traj 61
Traj 62
Traj 63
Traj 64
Traj 65
Traj 66
Traj 67
Traj 68
Traj 69
Traj 70
Traj 71
Traj 72
Traj 73
Traj 74
Traj 75
Traj 76
Traj 77
Traj 78
Traj 79
Traj 80
Traj 81
Traj 82
Traj 83
Traj 84
Traj 85
Traj 86
Traj 87
Traj 88
Traj 89
Traj 90
Traj 91
Traj 92
Traj 93
Traj 94
Traj 95
Traj 96
Traj 97
Traj 98
Traj 99
Traj 100
Traj 101
Traj 102
Traj 103
Traj 104
Traj 105
Traj 106
Traj 107
Traj 108
Traj 109
Traj 110
Traj 111
Traj 112
Traj 113
Traj 114
Traj 115
Traj 116
Traj 117
Traj 118
Traj 119
Traj 120
Traj 121
Traj 122
Tra

[1986,
 3308,
 3308,
 2373,
 12566,
 12566,
 1986,
 5473,
 1986,
 1986,
 1986,
 1986,
 6914,
 3651,
 1986,
 4691,
 1986,
 4691,
 1986,
 239,
 9348,
 9348,
 9348,
 9348,
 239,
 239,
 239,
 239,
 37206,
 1414,
 2280,
 37206,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 9348,
 9348,
 9348,
 1780,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 9348,
 1414,
 1414,
 3938,
 9348,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 9348,
 9348,
 9348,
 9348,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 9348,
 3259,
 1253,
 5070,
 2280,
 1780,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 3319,
 1165,
 6681,
 6681,
 6634,
 1166,
 1019,
 1166,
 1019,
 1253,
 5624,
 171,
 1260,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 219,
 219,
 219,
 1124,
 1253,
 1253,
 219,
 902,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 1780,
 239,
 239,
 239,
 239,
 239,
 239,
 239,
 239

In [203]:
%%time
# 统计vocab_size, 重新编号
trajs = []
path = './CDR/processed/trj_vocab_cdr.h5'
path = '../data/trj_vocab.h5'
with open(path, 'r') as f:
    srcstream = f.readlines()
    for s in srcstream:
        s = [int(x) for x in s.strip().split()]
        trajs = trajs + s
f.close()
trajs

KeyboardInterrupt: 

In [125]:
# 获取loc_index对应的new_index
result = Counter(trajs)
result_dict = dict(result)
df = pd.DataFrame(result_dict.keys())
df[1] = list(df.index)
df.columns = ['loc_index','new_index']
# df = df.set_index('index')

In [126]:
df

loc_index  new_index
0         1986          0
1         3308          1
2         2373          2
3        12566          3
4         5473          4
..         ...        ...
577       5732        577
578        713        578
579        395        579
580        542        580
581      25309        581

[582 rows x 2 columns]

In [127]:
# 保存loc_index_cdr_582.csv
lon_lat =  pd.read_csv('./CDR/jinchengFilteredLoc.csv')[['loc_index','longitude', 'latitude']]
loc_index_cdr = pd.merge(df, lon_lat, on='loc_index', how='left')
loc_index_cdr.to_csv('./CDR/processed/loc_index_cdr_582.csv')


loc_index  new_index   longitude   latitude
0         1986          0  112.843055  35.518888
1         3308          1  112.848055  35.515277
2         2373          2  112.830700  35.503100
3        12566          3  112.849166  35.538055
4         5473          4  112.835489  35.512832
..         ...        ...         ...        ...
577       5732        577  112.923810  35.799920
578        713        578  112.538577  35.624332
579        395        579  112.674264  35.483532
580        542        580  112.520000  35.504444
581      25309        581  112.667406  35.689075

[582 rows x 4 columns]

In [108]:
# 用new_index重新给数据集编号
trajs = dataset['trajectory']
labels = np.array(dataset['label']).T
srcfile = []
mtafile = []

In [109]:
%%time
replace_dict = dict(zip(loc_index_cdr['loc_index'], loc_index_cdr['new_index']))
for i, traj in enumerate(trajs):
    print(f'Traj {i}')
    traj_list = traj.split()
    traj_list = list(filter(lambda x: x != '[PAD]', traj.split(' ')))
    traj_list = list(map(lambda x: replace_dict[int(x)], traj_list))
    # 删掉逗号，以string形式保存
    traj_list = str(traj_list)[1:-1]
    traj_list = list((filter(lambda x: x != ',', traj_list)))
    traj_list= ''.join(traj_list)
    print(traj_list)
    srcfile.append(traj_list)

Traj 0


KeyError: 1986

In [110]:
mtafile = np.array(len(trajs)*[(81.43, 269.48)])
train_length = int(len(trajs)*0.85)

train_src = srcfile[0:train_length]
val_src = srcfile[train_length:]

In [111]:
np.savetxt ('./CDR/processed/train.src', train_src, fmt='%s')
np.savetxt ('./CDR/processed/train.trg', train_src, fmt='%s')
np.savetxt ('./CDR/processed/train.mta', mtafile[0:train_length], fmt='%f')
np.savetxt ('./CDR/processed/val.src', val_src, fmt='%s')
np.savetxt ('./CDR/processed/val.trg', val_src, fmt='%s')
np.savetxt ('./CDR/processed/val.mta', mtafile[train_length:], fmt='%f')

np.savetxt ('./CDR/processed/trj_vocab_cdr.h5', srcfile, fmt='%s')
with open('./CDR/processed/labels_cdr.pkl', 'wb') as file:
    pickle.dump(labels, file)

In [121]:
loc_index_cdr

loc_index  new_index   longitude   latitude
loc_index                                             
0                  0          0  112.836944  35.465833
1                  1          1         NaN        NaN
2                  2          2  112.780310  35.481750
3                  3          3         NaN        NaN
4                  4          4  112.831666  35.460555
...              ...        ...         ...        ...
577              577        577         NaN        NaN
578              578        578         NaN        NaN
579              579        579         NaN        NaN
580              580        580         NaN        NaN
581              581        581  112.522000  35.489100

[582 rows x 4 columns]

### 计算vocab-dist

In [114]:
# 计算vocab-dist
from math import radians, cos, sin, asin, sqrt
from scipy.spatial.distance import  cdist

def geo_distance(c_i, c_j):
    lng1, lat1 = c_i[0], c_i[1]
    lng2, lat2 = c_j[0], c_j[1]
    #lng1,lat1,lng2,lat2 = (120.12802999999997,30.28708,115.86572000000001,28.7427)
    lng1, lat1, lng2, lat2 = map(radians, [float(lng1), float(lat1), float(lng2), float(lat2)]) # 经纬度转换成弧度
    dlon=lng2-lng1
    dlat=lat2-lat1
    a=sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    distance=2*asin(sqrt(a))*6371*1000 # 地球平均半径，6371km
    distance=round(distance,3)
    # print(c_i, c_j, distance)
    return distance


In [135]:
%%time
dataset_name = 'CDR'
loc_index_cdr = pd.read_csv('./CDR/processed/loc_index_cdr_582.csv')
loc_a = loc_index_cdr[['longitude','latitude']].values.tolist()
loc_b = loc_a
dm = cdist(loc_a, loc_b, lambda loc_a, loc_b: geo_distance(loc_a, loc_b))
dm = pd.DataFrame(dm, columns=[i for i in range(len(loc_a))])
dm.index = loc_index_cdr.index
dm.index.name = 'loc_index'
dm.to_hdf(f'./{dataset_name}/processed/vocab-dist.h5', key='data')


CPU times: user 766 ms, sys: 3.4 ms, total: 769 ms
Wall time: 768 ms


In [144]:
dm

0          1          2          3          4          5    \
loc_index                                                                     
0              0.000    604.985   2081.469   2201.849    960.410   3285.132   
1            604.985      0.000   2073.902   2534.793   1169.387   3523.525   
2           2081.469   2073.902      0.000   4230.877   1165.742   1730.869   
3           2201.849   2534.793   4230.877      0.000   3065.638   5077.874   
4            960.410   1169.387   1165.742   3065.638      0.000   2367.764   
...              ...        ...        ...        ...        ...        ...   
577        32089.718  32382.413  34060.219  29888.601  32904.955  34418.051   
578        29930.520  30505.076  29663.543  29680.952  29578.943  28082.828   
579        15777.324  16123.766  14328.795  16952.152  14954.516  12644.146   
580        29284.535  29718.111  28125.342  30023.547  28571.948  26397.658   
581        24704.097  25302.643  25409.304  23493.792  24799.052  24351.312   

                 6          7          8          9    ...        572  \
loc_index                                              ...              
0           1677.292    933.871   6195.311   6119.453  ...  31716.589   
1           1533.140    401.852   5596.226   5543.552  ...  32007.622   
2            634.047   1858.691   5942.068   5531.829  ...  33689.271   
3           3877.893   2934.853   7664.189   7810.946  ...  29515.294   
4            944.014   1169.421   6207.650   5976.322  ...  32533.497   
...              ...        ...        ...        ...  ...        ...   
577        33762.397  32769.395  36086.584  36700.112  ...    387.262   
578        30142.579  30690.001  35601.039  35099.238  ...  39712.541   
579        14960.020  16065.499  19347.396  18523.437  ...  41470.923   
580        28739.334  29730.107  33438.962  32643.680  ...  48852.633   
581        25646.055  25626.383  30898.850  30769.874  ...  26052.452   

                 573        574        575        576        577        578  \
loc_index                                                                     
0          31063.937  31244.707  32802.419  31724.473  32089.718  29930.520   
1          31352.393  31536.075  33057.709  32011.482  32382.413  30505.076   
2          33039.982  33217.159  34813.528  33701.999  34060.219  29663.543   
3          28862.413  29043.439  30602.917  29522.856  29888.601  29680.952   
4          31883.433  32061.419  33650.475  32545.147  32904.955  29578.943   
...              ...        ...        ...        ...        ...        ...   
577         1058.714    849.452   2363.991    503.300      0.000  39886.409   
578        39396.045  39386.127  42009.727  39896.631  39886.409      0.000   
579        40910.543  41021.508  43190.577  41559.352  41787.550  19894.486   
580        48411.269  48458.148  50944.832  48997.456  49098.657  13436.422   
581        25754.020  25735.922  28368.580  26240.699  26218.040  13685.950   

                 579        580        581  
loc_index                                   
0          15777.324  29284.535  24704.097  
1          16123.766  29718.111  25302.643  
2          14328.795  28125.342  25409.304  
3          16952.152  30023.547  23493.792  
4          14954.516  28571.948  24799.052  
...              ...        ...        ...  
577        41787.550  49098.657  26218.040  
578        19894.486  13436.422  13685.950  
579            0.000  14158.129  22863.751  
580        14158.129      0.000  24476.825  
581        22863.751  24476.825      0.000  

[582 rows x 582 columns]

In [205]:
%%time
V = [np.array(10*[i]) for i in range(4)]
D = 4*[np.zeros(10)]
for i in range(len(dm)):
    print(f'Traj: {i}')
    tmp = dm[i].sort_values()[:10]
    v = tmp.index.to_numpy()
    d = tmp.values
    V.append(v)
    D.append(d)
V, D = np.array(V), np.array(D)

Traj: 0
Traj: 1
Traj: 2
Traj: 3
Traj: 4
Traj: 5
Traj: 6
Traj: 7
Traj: 8
Traj: 9
Traj: 10
Traj: 11
Traj: 12
Traj: 13
Traj: 14
Traj: 15
Traj: 16
Traj: 17
Traj: 18
Traj: 19
Traj: 20
Traj: 21
Traj: 22
Traj: 23
Traj: 24
Traj: 25
Traj: 26
Traj: 27
Traj: 28
Traj: 29
Traj: 30
Traj: 31
Traj: 32
Traj: 33
Traj: 34
Traj: 35
Traj: 36
Traj: 37
Traj: 38
Traj: 39
Traj: 40
Traj: 41
Traj: 42
Traj: 43
Traj: 44
Traj: 45
Traj: 46
Traj: 47
Traj: 48
Traj: 49
Traj: 50
Traj: 51
Traj: 52
Traj: 53
Traj: 54
Traj: 55
Traj: 56
Traj: 57
Traj: 58
Traj: 59
Traj: 60
Traj: 61
Traj: 62
Traj: 63
Traj: 64
Traj: 65
Traj: 66
Traj: 67
Traj: 68
Traj: 69
Traj: 70
Traj: 71
Traj: 72
Traj: 73
Traj: 74
Traj: 75
Traj: 76
Traj: 77
Traj: 78
Traj: 79
Traj: 80
Traj: 81
Traj: 82
Traj: 83
Traj: 84
Traj: 85
Traj: 86
Traj: 87
Traj: 88
Traj: 89
Traj: 90
Traj: 91
Traj: 92
Traj: 93
Traj: 94
Traj: 95
Traj: 96
Traj: 97
Traj: 98
Traj: 99
Traj: 100
Traj: 101
Traj: 102
Traj: 103
Traj: 104
Traj: 105
Traj: 106
Traj: 107
Traj: 108
Traj: 109
Traj: 110


In [206]:
print(V.shape)

(586, 10)


In [204]:
import os
import torch
knearestvocabs = '../data/geolife-vocab-dist-cell300.h5'
assert os.path.isfile(knearestvocabs),\
    "{} does not exist".format(knearestvocabs)
with h5py.File(knearestvocabs, 'r') as f:
    V, D = f["V"], f["D"]
    V = np.array(V)
    D = np.array(D)
    # V, D = torch.LongTensor(np.array(V)), torch.FloatTensor(np.array(D))
print(V.shape)
print(D)

(1319, 10)
[[   0.            0.            0.         ...    0.
     0.            0.        ]
 [   0.            0.            0.         ...    0.
     0.            0.        ]
 [   0.            0.            0.         ...    0.
     0.            0.        ]
 ...
 [   0.         1272.79220614 2121.32034356 ... 3818.37661841
  3911.52144312 4036.08721412]
 [   0.          670.82039325  848.52813742 ... 5100.
  7061.16137756 7080.25423272]
 [   0.          300.          600.         ...  948.68329805
   948.68329805 1081.66538264]]


In [196]:
print(V)

[[  0   0   0 ...   0   0   0]
 [  1   1   1 ...   1   1   1]
 [  2   2   2 ...   2   2   2]
 ...
 [579 374 458 ... 298 514 394]
 [580 363 556 ...  41 331 311]
 [581 351 457 ... 319 318 320]]


In [197]:

with h5py.File('./CDR/processed/cdr-vocab-dist-582.h5', 'w') as h5f:
    h5f.create_dataset('V', data=V)
    h5f.create_dataset('D', data=D)

In [198]:
# print(V)

with h5py.File('./CDR/processed/cdr-vocab-dist-582.h5', 'r') as f:
    V, D = f["V"], f["D"]
    V = np.array(V)
    D = np.array(D)

[[    0.        0.        0.    ...     0.        0.        0.   ]
 [    0.        0.        0.    ...     0.        0.        0.   ]
 [    0.        0.        0.    ...     0.        0.        0.   ]
 ...
 [    0.     2873.926  3411.94  ...  4658.037  4846.657  5038.047]
 [    0.      592.885  1715.755 ...  5102.859  5294.06   5538.841]
 [    0.     3197.446  5618.196 ...  9512.431  9682.75  10177.194]]
